name: israel-acosta
favicon: null
layout_spectrum: 0.50088
typography_spectrum: 0.75226
title: IT Support | Vancouver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a423f'
    - '#ffffff'
    - '#bebab9'
    - '#f05f40'
    - '#f69e8c'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
